// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvwicnmmhaydbfmabbtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2d2ljbm1taGF5ZGJmbWFiYnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTY0MjMsImV4cCI6MjA2MzE3MjQyM30._TVi5i3y4uC6oTKX_C-SF9df5_dlng1jLF4e2FawH8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);